name: search
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  about:
    path: ../about
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  dartz: ^0.10.0-nullsafety.2
  equatable: ^2.0.3
  google_fonts: ^2.1.0
  flutter_rating_bar: ^4.0.0
  cached_network_image: ^3.0.0
  get_it: ^7.1.3
  sqflite: ^2.0.0+3
  rxdart: ^0.27.1
  provider: ^5.0.0
  path_provider: ^2.0.2
  encrypt: ^5.0.1
  flutter_bloc: ^7.0.1
  firebase_core: ^1.6.0
  firebase_crashlytics: ^2.6.3

dev_dependencies:
  mockito: ^5.0.8
  build_runner: ^2.0.4
  bloc_test: ^8.0.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
